[nitpick.JSONFile]
file_names = ["package.json"]

["package.json"]
contains_keys = ["name", "version", "repository.type", "repository.url", "release.plugins"]

["package.json".contains_json]
commitlint = """
  {
    "extends": [
      "@commitlint/config-conventional"
    ]
  }
"""
