# https://github.com/marketplace/actions/release-notes-preview
name: Release-Notes-Preview

on:
  pull_request:
    # This workflow is not working for some reason. It is stuck with this message:
    #  Release Notes Confirmation Pending â€” awaiting release notes review
    #  Keeping the YAML file to check back again in the future
    branches: [release-notes-preview-is-not-working] # [develop]
  issue_comment:
    types: [edited]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow --tags
      - uses: snyk/release-notes-preview@v1.6.2
        with:
          releaseBranch: develop
        env:
          GITHUB_PR_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
